import { Inter } from "next/font/google";
import "./globals.css";
import ThemeClient from "./ providers/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Customer Support Bot",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeClient>
        <body style={{overflowY: 'hidden'}} className={inter.className}>{children}</body>
      </ThemeClient>
    </html>
  );
}
